export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_DETAIL = "CATEGORY_DETAIL";
export const SET_CATEGORY_NAME = "SET_CTAEGORY_NAME";
