export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_DETAIL_PRODUCT = "FETCH_DETAIL_PRODUCT";
export const POST_COMMENT = "POST_COMMENT";
export const INSERT_PRODUCT = "INSERT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EMPTY_PRODUCT = "EMPTY_PRODUCT";
